### ISSUE TITLE
Title: add some easy and understanding fonts 

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [Daksh777/TakeABreak#37]
### Is your feature request related to a problem? Please describe.

suppose you are using some easy and understanding  fonts so everyone will reachout to you.

### Describe the solution you'd like.

i  am using best  cool template and very easy word for understanding purpose.

### Describe alternatives you've considered.

i have already told you  i  am using best and easy things.

### Add any other context or screenshots about the feature request here.

this time i have not any screenshots right now. but you assigned me definitely i will work on

**Comment by Daksh777** [comment]
Can you please elaborate more @Khushbu-kumari-87090?

**Comment by rv602** [comment]
hey @Daksh777 , Rajagopalan here, a GSSOC 2022 participant.

I wish to take up this issue of adding some easy and understanding fonts to your website.

I'll use the best fonts and best practices to improve the font throughout your website. I'll also use font-embedding via google fonts so that the font can be rendered on any device in the way we exactly want it to look. 

I'll also use the relative-sizing rather than specifying font-size via pixels so that responsiveness can be taken care of.

**Comment by Daksh777** [comment]
I do not wish to change the fonts, @rv602.
The fonts are already optimised for mobiles so I don't think it is a problem.
